### DISCUSSION TITLE
How to configure cross-resource references for multi-layer reference relationships

### DISCUSSION THREAD

**Discussion by jingliming** [crossplane/upjet#486] [Q&A] [answered]
as the terraform example show，I try to generate managed resource with upjet, if i want to config the `zone_mappings` as a cross-resource reference in alicloud_alb_load_balancer,  How can I achieve this?
```
variable "name" {
  default = "terraform-example"
}

data "alicloud_resource_manager_resource_groups" "default" {
}

data "alicloud_alb_zones" "default" {
}

resource "alicloud_vpc" "default" {
  vpc_name   = var.name
  cidr_block = "10.4.0.0/16"
}

resource "alicloud_vswitch" "default" {
  count        = 2
  vpc_id       = alicloud_vpc.default.id
  cidr_block   = format("10.4.%d.0/24", count.index + 1)
  zone_id      = data.alicloud_alb_zones.default.zones[count.index].id
  vswitch_name = format("${var.name}_%d", count.index + 1)
}

resource "alicloud_alb_load_balancer" "default" {
  load_balancer_edition  = "Basic"
  address_type           = "Internet"
  vpc_id                 = alicloud_vpc.default.id
  address_allocated_mode = "Fixed"
  resource_group_id      = data.alicloud_resource_manager_resource_groups.default.groups.0.id
  load_balancer_name     = var.name
  load_balancer_billing_config {
    pay_type = "PayAsYouGo"
  }
  modification_protection_config {
    status = "NonProtection"
  }
  zone_mappings {
    vswitch_id = alicloud_vswitch.default.0.id
    zone_id    = data.alicloud_alb_zones.default.zones.0.id
  }
  zone_mappings {
    vswitch_id = alicloud_vswitch.default.1.id
    zone_id    = data.alicloud_alb_zones.default.zones.1.id
  }
  tags = {
    Created = "TF"
  }
}
```

**Comment by sergenyalcin** [comment]
@jingliming Do you mean whole `zone_mappings` block or `vswitch_id` field in the `zone_mappings` block?

**Reply by sergenyalcin** [reply, marked as answer]
If you want to generate a reference for the `vswitch_id` field, then you need to add the following type of configuration fir this:

```go
r.References["zone_mappings.vswitch_id"] = config.Reference{
	TerraformName:     "alicloud_vswitch",
}
```

**Reply by jingliming** [reply]
@sergenyalcin Thanks for your reply. For a dependency with only a single attribute, it seems to work, but there is also a zoneId attribute in this example. I tried to configure it this way, but it did not work as expected. What should I do?
```
p.AddResourceConfigurator("alicloud_alb_load_balancer", func(r *config.Resource) {
		r.ShortGroup = string(common.LOADBALANCER)
		r.Kind = "ALBInstance"
		r.References["vpc_id"] = config.Reference{
			TerraformName: "alicloud_vpc",
		}
		r.References["zone_mappings.vswitch_id"] = config.Reference{
			TerraformName: "alicloud_vswitch",
		}
		r.References["zone_mappings.zone_id"] = config.Reference{
			TerraformName: "alicloud_vswitch",
		}
		r.UseAsync = true
	})
```
the generated manifest yaml is:
```
    zoneMappings:
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: default
      zoneIdSelector:
        matchLabels:
          testing.upbound.io/example-name: alicloud_alb_zones
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: default
      zoneIdSelector:
        matchLabels:
          testing.upbound.io/example-name: alicloud_alb_zones
```
The expected configuration should be that zoneId is belong to the vSwitch where it is selected by the vswitchIdSelector. ZoneId could find in the status.atProvider.zoneId of vSwitch

https://registry.terraform.io/providers/aliyun/alicloud/1.247.0/docs/resources/alb_load_balancer
The zone_mappings supports the following:
allocation_id - (Optional, Computed, Available since v1.243.0) The ID of the EIP instance.
eip_type - (Optional, Computed, Available since v1.243.0) The type of the EIP instance.
intranet_address - (Optional, Computed, Available since v1.243.0) IPv4 private network address.
vswitch_id - (Required) The ID of the vSwitch that corresponds to the zone. Each zone can use only one vSwitch and subnet.
zone_id - (Required) The ID of the zone to which the SLB instance belongs.

**Reply by jingliming** [reply]
Maybe another way is to not use labelSelector for ZoneId, and then use ZoneId as the value of label to query vSwitch, like this:
```
apiVersion: vpc.alicloud.crossplane.io/v1alpha1
kind: VSwitch
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/database
  labels:
    testing.upbound.io/example-name: mingyuan-iac
    testing.upbound.io/zone-id: cn-hangzhou-h
  name: mingyuan-iac-vswitch
spec:
  ......
```
```
apiVersion: loadbalancer.alicloud.crossplane.io/v1alpha1
kind: ALBInstance
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/albinstance
  labels:
    testing.upbound.io/example-name: mingyuan-iac
  name: mingyuan-iac
spec:
  forProvider:
    ......
    zoneMappings:
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/zone-id: cn-hangzhou-h
      zoneId: cn-hangzhou-h
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/zone-id: cn-hangzhou-i
      zoneId: cn-hangzhou-i
```
