### DISCUSSION TITLE
My generated resource has a error while reconciling，How to fix this error in generated resource config?

### DISCUSSION THREAD

**Discussion by jingliming** [crossplane/upjet#487] [Q&A]
The error message is:
```
conditions:
  - lastTransitionTime: "2025-04-17T11:02:50Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-04-17T11:02:56Z"
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource alicloud_alb_server_group.mingyuan-iac has lifecycle.prevent_destroy
      set, but the plan calls for this resource to be destroyed. To avoid this error
      and continue with the plan, either disable lifecycle.prevent_destroy or reduce
      the scope of the plan using the -target option.'
    reason: ReconcileError
    status: "False"
    type: Synced
```
My Resource config is:
```
p.AddResourceConfigurator("alicloud_alb_server_group", func(r *config.Resource) {
		r.ShortGroup = string(common.LOADBALANCER)
		r.Kind = "ALBServerGroup"
		r.References["vpc_id"] = config.Reference{
			TerraformName: "alicloud_vpc",
		}
		r.UseAsync = true
	})
```
My Resource manifest is:
```
apiVersion: loadbalancer.alicloud.crossplane.io/v1alpha1
kind: ALBServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/alblistener
  labels:
    testing.upbound.io/example-name: mingyuan-iac
  name: mingyuan-iac
spec:
  forProvider:
    stickySessionConfig:
      - cookie: tf-example
        stickySessionEnabled: true
        stickySessionType: Server
    healthCheckConfig:
      - healthCheckCodes:
          - http_2xx
          - http_3xx
          - http_4xx
        healthCheckConnectPort: 80
        healthCheckEnabled: true
        healthCheckHost: tf-example.com
        healthCheckHttpVersion: HTTP1.1
        healthCheckInterval: 2
        healthCheckMethod: HEAD
        healthCheckPath: /tf-example
        healthCheckProtocol: HTTP
        healthCheckTimeout: 5
        healthyThreshold: 3
        unhealthyThreshold: 3
    protocol: HTTP
    serverGroupName: mingyuan-iac
    servers:
      - description: mingyuan-iac
        port: 80
        serverId: 172.16.0.74
        serverType: Ecs
        weight: 10
    tags:
      Created: crossplane
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mingyuan-iac
```
