### ISSUE TITLE
Observe policy is less useful than TF data resources

### ISSUE THREAD

**Issue by jond3k** [crossplane/upjet#283]
### What happened?

I'd like to get the equivalent behaviour to [data_google_tags_tag_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/tags_tag_key)

The crossplane way to simulate this behaviour is to set the resource as observe-only and use external-name.

However, this isn't semantically the same. Instead it's converted into `terraform import resource ${external_name}` by upjet.

The problem with this is that imports often aren't as good at resolving resources as data resources. In this case, the data resource will resolve a `namespacedName` like `${org_id}/${short_name}` but import will only resolve a `name` like `tagKeys/${id}` but this is much less portable as the number changes all the time.

*Perhaps it would be better to make external-name optional for observe-only and use the data resources instead of import if they're available*?

### How can we reproduce it?

Using a resource which has multiple forms of ID and no support for these IDs in `terrafrom import`, like [google_tags_tag_key](https://github.com/upbound/provider-gcp/pull/397) we need an equivalent to:

```
data "google_tags_tag_key" "environment_tag_key"{
  parent = "organizations/567890"
  short_name = "myTagName"
}
```

This fails as `namespacedName` isn't supported for import by Terraform:

```
apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagKey
metadata:
  name: with-namespaced-name
  annotations:
    crossplane.io/external-name: 567890/myTagName
spec:
  managementPolicies: [Observe]
  forProvider: {}
``` 

This succeeds because `name` is supported:

```
apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagKey
metadata:
  name: with-name
  annotations:
    crossplane.io/external-name: tagKeys/123456
spec:
  managementPolicies: [Observe]
  forProvider: {}
``` 

Alternatively, it would be nice if this would work but it currently fails as observe-only only seems to work with an external-name:

```
apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagKey
metadata:
  name: with-no-name
spec:
  managementPolicies: [Observe]
  forProvider:
    parent: organizations/567890
    short_name: myTagName
```
