### ISSUE TITLE
Transient references do not work

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/upjet#55]
When there is a transient reference in the Terraform documentation like below, we cannot add the reference for the correct resource.

```
resource "aws_network_interface_sg_attachment" "sg_attachment" {
  security_group_id    = aws_security_group.sg.id
  network_interface_id = aws_instance.instance.primary_network_interface_id
}
```

### What happened?
In the examples-generated folder, we see the following manifest:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterfaceSgAttachment
metadata:
  labels:
    testing.upbound.io/example-name: sg_attachment
  name: sg-attachment
spec:
  forProvider:
    networkInterfaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    region: us-west-1
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sg

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    ami: ${data.aws_ami.ami.id}
    instanceType: t2.micro
    region: us-west-1
    tags:
      type: terraform-test-instance

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    testing.upbound.io/example-name: sg
  name: sg
spec:
  forProvider:
    region: us-west-1
    tags:
      type: terraform-test-security-group

---

```
where `networkInterfaceIdSelector` is referring to an EC2 instance.

cc: @ulucinar
