### ISSUE TITLE
Random external name annotations got broken after injecting references into example manifests

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/upjet#68]
### What happened?

Before enabling unified example manifests, we could be able to generate random names with `RandRFC1123Subdomain`.
```
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
  name: example
spec:
  forProvider:
    region: us-west-1
```
  Now, those annotations are displayed like below:

```
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    region: us-west-1
    tags:
      Environment: Dev
      Name: My bucket
```
### How can we reproduce it?

By checking `provider-aws/examples-generated/s3/bucket.yaml` after running `make generate`.
