### ISSUE TITLE
Support multiple reference Types

### ISSUE THREAD

**Issue by donovanmuller** [crossplane/upjet#95]
### What problem are you facing?

Currently, you can add a single, explicit reference, to another resource like [this](https://github.com/upbound/official-providers/blob/dcb8ab9522ec0d8b23b866477352516550f3ece1/provider-gcp/config/cloudscheduler/config.go#L10-L14) example for `google_cloud_scheduler_job`:

```go
	p.AddResourceConfigurator("google_cloud_scheduler_job", func(r *config.Resource) {
		r.References["pubsub_target.topic_name"] = config.Reference{
			Type: "github.com/upbound/official-providers/provider-gcp/apis/pubsub/v1beta1.Topic",
		}
	})
```

However, some resources can accept references for multiple Types. In the example above, Both a `Topic` and a `LiteTopic` are supported. Upjet currently does not allow multiple references, of different Types, for a single argument.

### How could Terrajet help solve your problem?

Allow specifying multiple supported reference Types for an argument. E.g.

```go
	p.AddResourceConfigurator("google_cloud_scheduler_job", func(r *config.Resource) {
		r.References["pubsub_target.topic_name"] = []config.Reference{
			config.Reference{
				Type: "github.com/upbound/official-providers/provider-gcp/apis/pubsub/v1beta1.Topic",
			},
			config.Reference{
				Type: "github.com/upbound/official-providers/provider-gcp/apis/pubsub/v1beta1.LiteTopic",
			},
		}
```

Terrajet community example [here](https://crossplane.slack.com/archives/CEG3T90A1/p1663042089769839).

**Comment by csantanapr** [comment]
I hit this problem today with the [SubscriptionFilter](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.31.0/resources/cloudwatchlogs.aws.upbound.io/SubscriptionFilter/v1beta1)

The filter takes a `destinationArnRef` or `destinationArnSelector` is based on [[destinationArn](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutSubscriptionFilter.html#API_PutSubscriptionFilter_RequestSyntax)](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutSubscriptionFilter.html#API_PutSubscriptionFilter_RequestSyntax)
The ARN of the destination to deliver matching log events to. Currently, the supported destinations are:
- An **Amazon Kinesis stream** belonging to the same account as the subscription filter, for same-account delivery.
- A logical destination (specified using an ARN) belonging to a different account, for cross-account delivery.
- A **Kinesis Data Firehose  delivery stream** belonging to the same account as the subscription filter, for same-account delivery.
- A **Lambda function** belonging to the same account as the subscription filter, for same-account delivery.
The destination can be of kind Lambda, Kinesis Stream, Kinesis Firehose, or OpenSearch 

I want to create a subscription for destination to **Kinesis Data Firehose** but only **Amazon Kinesis stream** is supported

I tried the following, having a Delivery system with labels
```yaml
apiVersion: firehose.aws.upbound.io/v1beta1
kind: DeliveryStream
metadata:
  labels:
    crossplane.io/claim-name: test-logs-firehose-s3-lambda
    crossplane.io/claim-namespace: default
    firehoseapps.awsblueprints.io/app: firehose

...
```
I create a subscription with destinationArnSelector
```yaml
apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: SubscriptionFilter
metadata:
  name: dynatrace-aws-logs-test
spec:
  forProvider:
    destinationArnSelector:
      matchLabels:
        crossplane.io/claim-name: test-logs-firehose-s3-lambda
        crossplane.io/claim-namespace: default
        firehoseapps.awsblueprints.io/app: firehose
    filterPattern: ""
    logGroupName: "/aws/eks/crossplane-blueprints/cluster"
    name: "dynatrace-aws-logs-test"
    region: "us-east-1"
...
```
I get error 
```
    message: 'cannot resolve references: mg.Spec.ForProvider.DestinationArn: no resources
      matched selector'
    reason: ReconcileError
```
